name: Android Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev readline-common libgmp-dev libmpfr-dev libmpc-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 pillow

      - name: Build APK
        run: yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: SpyGame-APK
          path: bin/*.apk
