name: Build Spy Game APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # السيرفر الأسرع حالياً

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 # التحديث لـ 17 يتناسب مع السيرفر الجديد ويقلل وقت التعارض
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # --- ميزة السرعة القصوى: التخزين المؤقت ---
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libgdbm-dev libncursesw5-dev libffi-dev unzip zip autoconf automake libtool pkg-config libncurses5

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install "cython<3.0.0" buildozer

      - name: Build APK
        run: |
          # لم نحذف المجلدات هنا لنستفيد من الـ Cache في المرات القادمة
          yes | buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SpyGame-Final-APK
          path: bin/*.apk
